services:

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: crazyjob
      POSTGRES_PASSWORD: crazyjob
      POSTGRES_DB: crazyjob_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crazyjob"]
      interval: 3s
      timeout: 2s
      retries: 15

  test:
    build:
      context: .
      target: development
    command: >
      sh -c "
        crazyjob migrate &&
        pytest tests/ --cov=crazyjob --cov-report=xml -p no:warnings
      "
    environment:
      CRAZYJOB_DATABASE_URL: postgresql://crazyjob:crazyjob@db/crazyjob_test
    depends_on:
      db:
        condition: service_healthy
